###Importing of libraries

In [18]:
#data manipulation libraries
import pandas as pd
import numpy as np

#importing train and test splitting libraries
from sklearn.model_selection import train_test_split

#importing a text vectorizer form sklearn
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import classification_report

**Reading the dataset**

In [2]:
#reading the dataset
df = pd.read_csv('/content/drive/MyDrive/NLP CHATBOT/SPAM AND HAM EMAILS CLASSIFICATION/spam.csv')
#printing the first 5 rows of the dataset
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
#Getting the value counts of the category column
df['Category'].value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

- The dataset is imbalanced

In [4]:
#changing the categorical column to 0 and 1 values
df['spam'] = df['Category'].apply(lambda x: 1 if x == 'spam' else 0)
#checking the head of the dataset
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

- A new column from the Category column known as spam has been created

In [5]:
#splitting the dataset into trainjing and testing set
X_train,X_test, y_train,y_test = train_test_split( df.Message, df.Category, test_size = 0.25)
X_train.head()

3444    Your board is working fine. The issue of overh...
5289    Hey! Congrats 2u2. id luv 2 but ive had 2 go h...
245                 U don't remember that old commercial?
28      I'm back &amp; we're packing the car now, I'll...
4498                                                   Ok
Name: Message, dtype: object

In [6]:
#getting the shape of the training and testing set
print('shape of X_train is: ', X_train.shape)
print('shape of X_test is: ', X_test.shape)

shape of X_train is:  (4179,)
shape of X_test is:  (1393,)


In [7]:
type(X_train.values)

numpy.ndarray

In [8]:
print(X_train[:4])
print(type(X_train))

3444    Your board is working fine. The issue of overh...
5289    Hey! Congrats 2u2. id luv 2 but ive had 2 go h...
245                 U don't remember that old commercial?
28      I'm back &amp; we're packing the car now, I'll...
Name: Message, dtype: object
<class 'pandas.core.series.Series'>


In [10]:
#converting X_train to a vectorised matrix
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<4179x7534 sparse matrix of type '<class 'numpy.int64'>'
	with 55476 stored elements in Compressed Sparse Row format>

In [15]:
#converting x_test to a vectorised matrix
X_test_cv = v.transform(X_test.values)
X_test_cv

<1393x7534 sparse matrix of type '<class 'numpy.int64'>'
	with 17352 stored elements in Compressed Sparse Row format>

In [12]:
#convering it to an array
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0])

In [14]:
#converting X_train to an array
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0])

In [16]:
#converting X_test to an array
X_test_np = X_test_cv.toarray()
X_test_np[0]

array([0, 0, 0, ..., 0, 0, 0])

In [21]:
#using a naives bayes classifier
from sklearn.naive_bayes import MultinomialNB
#INITIALIZING THE MODEL
model = MultinomialNB()
#fitting the data
model.fit(X_train_cv, y_train)

MultinomialNB()

In [22]:
#Making predictions on the x_test
preds = model.predict(X_test_cv)
report = classification_report(preds, y_test)
print(report)

              precision    recall  f1-score   support

         ham       1.00      0.98      0.99      1217
        spam       0.90      0.98      0.94       176

    accuracy                           0.98      1393
   macro avg       0.95      0.98      0.96      1393
weighted avg       0.98      0.98      0.98      1393

